export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_BY_CATEGORY = 'GET_MOVIES_BY_CATEGORY';

export const DELETE_MOVIE = 'DELETE_MOVIE';
export const MOVIES_ERROR = 'MOVIES_ERROR';
export const SET_CATEGORY = 'SET_CATEGORY';
export const HANDLE_CHECK = 'HANDLE_CHECK';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const UPDATE_DISLIKES = 'UPDATE_DISLIKES';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const SET_MOVIES_PER_PAGE = 'SET_MOVIES_PER_PAGE';
